name: ✨ Nova funcionalidade
description: Sugira uma melhoria ou funcionalidade
labels: [enhancement]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta
      description: Como deveria funcionar?
    validations:
      required: true
